### ISSUE TITLE
Vidock ActiveX Error

### ISSUE THREAD

**Issue by AFaustini** [lee-soft/ViDock#5]
With the latest release, even when i put the wrapper in same folder, the program crashs with following error:
Run-time error '429":
ActiveX component can't create object
There is a way to fix it?

**Comment by lee-soft** [comment]
You need to register the GDIPlusWrapper DLL too, I will update the README. 

On 64bit systems, you need to run Command Prompt as administrator then type
cd c:\windows\syswow64 (push enter key)
On 32bit systems, you can skip the above step, then type 
regsvr32, followed by a space then drag the gdipluswrapper.dll to the command window. It will enter the full DLL Path. (push enter key)

Enjoy.

**Comment by AFaustini** [comment]
Now works!
But the menu bar thing doesn't work and when i maximize any program, the program overlaps the bar.

**Comment by lee-soft** [comment]
That's a separate issue, please open a new thread for that :)
